kind: Pod
apiVersion: v1
metadata:
  name: input
spec:
  initContainers:
    - name: create-input-topic
      image: golang:1.16
      command:
        - curl
      args:
        - -fvN
        - http://testapi:8378/kafka/create-topic?topic=input-topic
    - name: create-output-topic
      image: golang:1.16
      command:
        - curl
      args:
        - -fvN
        - http://testapi:8378/kafka/create-topic?topic=output-topic
  containers:
    - name: pump-topic
      image: golang:1.16
      command:
        - curl
      args:
        - -fvN
        - http://testapi:8378/kafka/pump-topic?topic=input-topic&sleep=500ms
