name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/cache@v2
        with:
          path: /home/runner/.cache/go-build
          key: GOCACHE-v2-${{ hashFiles('**/go.mod') }}
      - uses: actions/cache@v2
        with:
          path: /home/runner/go/pkg/mod
          key: GOMODCACHE-v2-${{ hashFiles('**/go.mod') }}
      - run: go version
      - run: go env
      - run: make kubebuilder name=linux
      - run: go mod download
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)

  lint:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36.0
          args: --verbose
      - run: git diff --exit-code

  # it = integration test
  it:
    runs-on: ubuntu-latest
    if: "true"
    strategy:
      fail-fast: false
      matrix:
        suite:
          - http-fmea
          - kafka-fmea
          - stan-fmea
        rep:
          - "0"
        include:
          - suite: db-e2e
          - suite: e2e
          - suite: examples
          - suite: http-stress
          - suite: hpa
          - suite: kafka-e2e
          - suite: kafka-stress
          - suite: s3-e2e
          - suite: stan-e2e
          - suite: stan-stress
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ hashFiles('**/go.mod') }}
      - name: Install and start K3S
        timeout-minutes: 3
        run: |
          curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.2+k3s1 INSTALL_K3S_CHANNEL=stable INSTALL_K3S_EXEC=--docker K3S_KUBECONFIG_MODE=644 sh -
          until kubectl cluster-info ; do sleep 10s ; done
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.2"
      - uses: actions/cache@v2
        with:
          path: /home/runner/.cache/go-build
          key: GOCACHE-v2-${{ hashFiles('**/go.mod') }}
      - uses: actions/cache@v2
        with:
          path: /home/runner/go/pkg/mod
          key: GOMODCACHE-v2-${{ hashFiles('**/go.mod') }}
      - run: make controller
      - run: make testapi
      - run: make deploy CONFIG=ci
      - run: make runner
      - run: make runtimes
        if: ${{matrix.suite == 'e2e' || matrix.suite == 'examples'}}
      - run: make wait
      - run: make test-${{matrix.suite}}
      - name: controller logs
        if: ${{ failure() }}
        run: kubectl -n argo-dataflow-system logs deploy/controller-manager -c manager
