name: Release

on:
  push:
    tags: [ v* ]
    branches: [ main ]

jobs:

  publish-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ controller, runner, go1-16, java16, python3-9 ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: docker build + push
        run: |
          tag=$(basename $GITHUB_REF)
          if [ $tag = "main" ]; then
            tag="latest"
          fi
          docker buildx build . --target ${{matrix.target}} --tag quay.io/argoproj/dataflow-${{matrix.target}}:$tag --push

  publish-release:
    runs-on: ubuntu-latest
    needs: [ publish-images ]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
        with:
          # 0 indicates all history for all branches and tags.
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make manifests changelog TAG=${GITHUB_REF##*/}
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v0') || contains(github.ref, 'rc') }}
          body_path: changelog
          files: |
            config/default.yaml
            config/quick-start.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
